#!/usr/bin/php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Application;

define('APP_ROOT_DIR', __DIR__);

$app = new Application("Generic Linux Backup", "0.0.1");
$app->add(new Pkj\LinuxGenericBackup\Commands\Filesystem("Filesystem backups"));
$app->add(new Pkj\LinuxGenericBackup\Commands\Mysql("Mysql backups"));
$app->run();
