#!/usr/bin/php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Application;

define('APP_ROOT_DIR', __DIR__);

$app = new Application("Generic Linux Backup", "1.0.0");
$app->add(new Pkj\LinuxGenericBackup\Commands\Backup("Create a backup"));
$app->run();
